api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: 'API Recettes'
    description: 'decription de pleine de recette delicieuse'
    version: '0.0.1'
    show_webby: false
    openapi:
        contact:
            name: fumant2000
            url: https://github.com/fumant2000
            email: erictiobo17@gmail.com